import Link from 'next/link';import {serverDb} from '../../lib/supabase';import {redirect} from 'next/navigation';import Scanner from '../../components/Scanner';import RemoverPresenca from '../../components/RemoverPresenca';
export default async function Portaria({searchParams}:{searchParams:Promise<{evento?:string}>}){
 const db=await serverDb();const {data:{user}}=await db.auth.getUser();if(!user)redirect('/login');
 const {data:operator}=await db.from('operadores').select('perfil').eq('user_id',user.id).single();const podeRemover=['admin','secretaria'].includes(operator?.perfil||'');
 const {data:ev}=await db.from('eventos').select('id,titulo,local,aberto').order('inicio',{ascending:false}).limit(100);
 const selected=(await searchParams).evento||ev?.find(e=>e.aberto)?.id||ev?.[0]?.id;const current=ev?.find(e=>e.id===selected);
 const {data:presencas}=current?await db.from('presencas').select('id,registrado_em,participantes(nome,categoria,congregacao)').eq('evento_id',current.id).order('registrado_em',{ascending:false}).limit(100):{data:[]};
 return <main><span className="eyebrow">PORTARIA • QR CODE</span><h1>Registrar presença</h1><p className="subtitle">Selecione uma reunião, leia o QR individual e confira a confirmação na tela.</p>
 {!current?<div className="empty">Nenhum evento disponível. <Link href="/eventos">Cadastre um evento →</Link></div>:
 <div className="portaria-grid"><aside className="card"><h2>Reunião selecionada</h2><p className="muted">Escolha onde registrar a entrada</p>{(ev||[]).map(e=><Link key={e.id} className="event-link" href={'/portaria?evento='+e.id}>{e.id===current.id?'● ':''}{e.titulo} — {e.local}</Link>)}<div className="section-head"><h2>Presenças confirmadas</h2><p>{presencas?.length??0} registros exibidos</p></div><div className="presence-list">{(presencas||[]).length===0?<p className="muted">Ainda não há entradas confirmadas.</p>:(presencas||[]).map((p:any)=><div className="presence-item" key={p.id}><div className="presence-person"><strong>{p.participantes?.nome||'Participante'}</strong><span>{new Date(p.registrado_em).toLocaleTimeString('pt-BR',{timeZone:'America/Cuiaba',hour:'2-digit',minute:'2-digit'})}</span></div>{podeRemover&&<RemoverPresenca id={p.id} evento={current.id} nome={p.participantes?.nome||'participante'}/>} </div>)}</div></aside><section className="card scan-panel"><span className="pill">● Leitor de entrada</span><h2 style={{marginTop:16}}>{current.titulo}</h2><p className="muted">{current.local}</p>{current.aberto?<Scanner evento={current.id}/>:<p className="empty">Portaria finalizada. As presenças podem ser consultadas e corrigidas ao lado, mas novos QR Codes não são aceitos.</p>}<p className="status-note">O código é conferido com o cadastro no Supabase. QR desconhecido, revogado ou já registrado não gera nova presença.</p></section></div>}</main>
}